#!/bin/sh

echo " "
echo "*************************************************************"
echo "*                                                           *"
echo "*              A betterprojectsfaster.com Talk              *"
echo "*              -------------------------------              *"
echo "*                                                           *"
echo "*   Eclipse OpenJ9: Memory Diet for Your JVM Applications   *"
echo "*     https://github.com/ksilz/bpf-talks-openj9-memory      *"
echo "*                                                           *"
echo "*************************************************************"
echo " "
echo "This container is part of a presentation about the the"
echo "Eclipse OpenJ9 JVM. Please see here for details:"
echo "https://github.com/ksilz/bpf-talks-openj9-memory"
echo " "
echo "This container runs a Spring Boot - Angular web application."
echo "JHipster (https://www.jhipster.tech) generated it."
echo "It tests JVM memory utilization of a monolith. "
echo " "
echo "This container uses this Java version:"
java -version
echo " "
echo "This container uses these Java options:"
echo "${JAVA_OPTS}"
echo " "
echo "The application will start in ${JHIPSTER_SLEEP}s..." && sleep ${JHIPSTER_SLEEP}
echo " "
echo "Running web application..."
java ${JAVA_OPTS} -jar /usr/app/simple-shop.jar
echo " "
echo " Done. "
echo " "
